image: nixos/latest

environment:
  # We need to enable flakes for our builds to work
  NIX_CONFIG: 'experimental-features = nix-command flakes'
  # We want to disable all colored output within the ci
  NO_COLOR: 'true'
  # See NO_COLOR
  TERM: 'dumb'

artifacts:
  # The debug build artifact
  - veil/result/bin/veil

tasks:
  # Build veil using the debug nix package
  - build: cd ~/veil && nix build $PWD#debug
